version: '3.7'
services:
  compiler:
    dns_search: 
      - vpnservice.company
      - f180.vpnservice.company
    build:
      dockerfile: ./../../guard/compiler.Dockerfile
      args:
        compiler_mode: musl
      target: compiler
    image: compiler
    hostname: wg
    init: no
    working_dir: /guard/scripts
    command: /entrypoint.sh
    volumes:
     - ./compiler.sh:/entrypoint.sh
     - /dev/net/tun:/dev/net/tun
     - ../../guard:/guard
    environment:
     - PATH=/guard/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    privileged: no
    restart: always
  wg:
    image: masipcat/wireguard-go:latest
    hostname: wg
    init: no
    working_dir: /guard/scripts
    sysctls:
     - net.ipv4.ip_forward=1
    volumes:
     - ./entrypoint.sh:/entrypoint.sh
     - ./wireguard:/etc/wireguard
     - /dev/net/tun:/dev/net/tun
     - ../../guard/.musl-bin/guard:/usr/bin/guard
     - ../../guard:/guard
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=debug
     - LISTEN_HOST=127.0.0.1
     - LISTEN_PORT=59222
     - PATH=/guard/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - 59222:59222/tcp
      - 59300:59300/udp
      - 59301:59301/udp
      - 59302:59302/udp
      - 59303:59303/udp
      - 59304:59304/udp
    privileged: yes
    restart: always

