version: '3.7'
services:
  wg:
    image: masipcat/wireguard-go:latest
    cap_add:
     - NET_ADMIN
     - SYS_MODULE       
    sysctls:
     - net.ipv4.ip_forward=1
    volumes:
     - ./entrypoint.sh:/entrypoint.sh
     - /dev/net/tun:/dev/net/tun
     # Folder with 'publickey', 'privatekey' and 'wg0.conf'
     - ./wireguard:/etc/wireguard
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=debug
    ports:
      - 41820:41820/udp
    # Uncomment the following line when 'AllowedIPs' is '0.0.0.0/0'
    # privileged: true
    restart: always

